//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;swagger&quot;:&quot;2.0&quot;,&quot;info&quot;:{&quot;version&quot;:&quot;v1&quot;,&quot;title&quot;:&quot;ExampleApi&quot;},&quot;host&quot;:&quot;microsoft-apiapp44519e77af114f2e8841c2153cfd0b92.azurewebsites.net:443&quot;,&quot;schemes&quot;:[&quot;https&quot;],&quot;paths&quot;:{&quot;/api/{version}/companies&quot;:{&quot;get&quot;:{&quot;tags&quot;:[&quot;Companies&quot;],&quot;operationId&quot;:&quot;Companies_GetCompanies&quot;,&quot;consumes&quot;:[],&quot;produces&quot;:[&quot;application/json&quot;,&quot;text/json&quot;,&quot;text/html&quot;,&quot;application/xml&quot;,&quot;text/xml&quot;],&quot;parameters&quot;:[{&quot;name&quot;:&quot;version&quot;,&quot;in&quot;:&quot;path&quot;,&quot;required&quot;:true,&quot;type&quot;:&quot;string&quot;}],&quot;responses&quot;:{&quot;200&quot;:{&quot;description&quot;:&quot;OK&quot;,&quot;schema&quot;:{&quot;$ref&quot;:&quot;#/definition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiSwaggerMetadata {
            get {
                return ResourceManager.GetString("ApiSwaggerMetadata", resourceCulture);
            }
        }
    }
}
